addons:
  artifacts:
    debug: true
    paths:
    - libs.zip
    - build.zip
    - testbuild.zip
    - jacoco.exec
    target_paths: 35f1eee9-de7d-411f-9af9-bc6cc20b986e
after_success:
- ' wget --content-disposition http://search.maven.org/remotecontent?filepath=org/jacoco/jacoco/0.7.7.201606060606/jacoco-0.7.7.201606060606.zip '
- ' unzip -o jacoco-0.7.7.201606060606.zip  '
- ' cd lib  '
- ' mv * ../  '
- ' cd ..  '
- ' chmod a+x *  '
- ' cd $PWD  '
- ' rm  ''jacoco.exec'''
- ' export JAVA_TOOL_OPTIONS=-javaagent:$PWD/jacocoagent.jar=destfile=$PWD/jacoco.exec,append=true  '
- ' travis_wait 720 mvn  test -Dmaven.test.failure.ignore=true -Djacoco.skip=true
  -Dcobertura.skip=true -Dmaven.clover.skip=true -Dmaven.javadoc.skip=true -Drat.skip=true
  -Drat.ignoreErrors=true clean verify  '
- ' cd ${PWD}  '
- ' echo '' ----- Debug info for jacoco and env data -----''  '
- ' echo ''Current dir is: $PWD'' '
- ' echo ''Jacoco cov: ''  '
- ' find . -name ''*.exec''  '
- ' echo '' ----------------------------------------------'' '
- ./df-build.sh
before_install:
- wget https://archive.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.zip
- unzip -qq apache-maven-3.3.9-bin.zip
- export M2_HOME=$PWD/apache-maven-3.3.9
- export PATH=$M2_HOME/bin:$PATH
branches: ''
cache:
  directories:
  - $HOME/.m2
  - $HOME/.m2
dist: trusty
install:
- mvn -B clean install -Dmaven.test.skip.exec
jdk:
- oraclejdk8
language: java
notifications:
  webhooks:
    on_failure: always
    on_start: always
    on_success: always
    urls:
    - http://insights-portal-insights-service-webserver-dev.public-swarm.devfactory.com/travisWebHookListener?build_id=35f1eee9-de7d-411f-9af9-bc6cc20b986e
script:
- mvn -B test -Pjacoco -Pweld -Pstandalone
- mvn -B test -Pjacoco -Powb -pl envs/se
- mvn -B test -Pjacoco -Pwildfly-8.x -pl envs/ee
- mvn -B test -Pjacoco -Pwildfly-9.x -pl envs/ee
- mvn -B test -Pjacoco -Pwildfly-10.x -pl envs/ee
- mvn -B test -Pjacoco -Pwildfly-camel -pl envs/ee
- mvn -B test -Pjacoco -Pkaraf,weld -pl envs/osgi/
sudo: required
# Modified by Insights Service at 2016-11-27 17:57:34.232156
