language: java

branches:
  only:
    - master

install:
  - mvn clean install -Dmaven.test.skip.exec

script:
  - mvn test -Pjacoco -Pweld
# disabled until OWB-1004 (repeatable qualifiers) is worked out
# - mvn test -Pjacoco -Powb -pl envs/se
  - mvn test -Pjacoco -Pwildfly -pl envs/ee

jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8

notifications:
  email:
    recipients:
      - antonin.stefanutti@gmail.com

after_success:
  - mvn jacoco:report -pl impl
  - mvn -N coveralls:jacoco