sudo: required
dist: trusty

language: java

cache:
  directories:
  - $HOME/.m2

branches:
  only:
    - master

install:
  - mvn -B clean install -Dmaven.test.skip.exec

script:
  - mvn -B test -Pjacoco -Pweld -Pstandalone
  - mvn -B test -Pjacoco -Powb -pl envs/se
  - mvn -B test -Pjacoco -Pwildfly-8.x -pl envs/ee
  - mvn -B test -Pjacoco -Pwildfly-9.x -pl envs/ee
  - mvn -B test -Pjacoco -Pwildfly-camel -pl envs/ee
  - mvn -B test -Pjacoco -Pkaraf,weld -pl envs/osgi/
#  - mvn -B test -Pjacoco -Pkaraf,owb -pl envs/osgi/

jdk:
  - openjdk8
  - oraclejdk8

notifications:
  email:
    recipients:
      - antonin.stefanutti@gmail.com

after_success:
  - mvn jacoco:report -pl impl
  - mvn -N coveralls:report