language: java

install:
  - mvn clean install -Dmaven.test.skip.exec

script:
  - mvn test -Pjacoco -Pweld
  - mvn test -Pjacoco -Powb

jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8

notifications:
  email:
    recipients:
      - antonin.stefanutti@gmail.com

after_success:
  - mvn jacoco:report
  - mvn -N coveralls:jacoco
